apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: anton
  name: anton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anton
  template:
    metadata:
      labels:
        app: anton
    spec:
      containers:
      - image: test:minikube
        name: test
    